//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tile.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tile.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Start Menu Tile Generator.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expose the configuration file.
        /// </summary>
        public static string ButtonCustomExposeConfigFile {
            get {
                return ResourceManager.GetString("ButtonCustomExposeConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload the configuration file.
        /// </summary>
        public static string ButtonCustomReloadConfigFile {
            get {
                return ResourceManager.GetString("ButtonCustomReloadConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate tiles.
        /// </summary>
        public static string ButtonGenerateTiles {
            get {
                return ResourceManager.GetString("ButtonGenerateTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset tiles.
        /// </summary>
        public static string ButtonResetTiles {
            get {
                return ResourceManager.GetString("ButtonResetTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup applications.
        /// </summary>
        public static string ButtonSearchApplications {
            get {
                return ResourceManager.GetString("ButtonSearchApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tiles configuration file was successfully exported to: {0}. You can now open this file, customize it and reload it to generate tiles with a custom look..
        /// </summary>
        public static string MessageExposedTilesConfigFile {
            get {
                return ResourceManager.GetString("MessageExposedTilesConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed exporting the tiles configuration file. Check that the file isn&apos;t already opened by another program..
        /// </summary>
        public static string MessageFailedExposingTilesConfigFile {
            get {
                return ResourceManager.GetString("MessageFailedExposingTilesConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application settings are invalid..
        /// </summary>
        public static string MessageInvalidSettings {
            get {
                return ResourceManager.GetString("MessageInvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tiles configuration is invalid..
        /// </summary>
        public static string MessageInvalidTilesConfig {
            get {
                return ResourceManager.GetString("MessageInvalidTilesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded the tiles configuration file..
        /// </summary>
        public static string MessageLoadedTilesConfigFile {
            get {
                return ResourceManager.GetString("MessageLoadedTilesConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to found applications to customize in the start menu..
        /// </summary>
        public static string MessageLookupNoApplication {
            get {
                return ResourceManager.GetString("MessageLookupNoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one application should be selected..
        /// </summary>
        public static string MessageNoApplicationSelected {
            get {
                return ResourceManager.GetString("MessageNoApplicationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tiles were generated, check settings or logs for additional information.
        ///If some applications already have custom tiles, you may need to enable the option &quot;Overwrite existing tiles&quot; to replace them..
        /// </summary>
        public static string MessageNoTiles {
            get {
                return ResourceManager.GetString("MessageNoTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the applications had custom tiles to reset..
        /// </summary>
        public static string MessageNoTilesToReset {
            get {
                return ResourceManager.GetString("MessageNoTilesToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tiles configuration file already exists. Do you want to overwrite it?.
        /// </summary>
        public static string MessageOverwriteTilesConfigFile {
            get {
                return ResourceManager.GetString("MessageOverwriteTilesConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}/{1} application(s) ({2}). Pin the applications on the start menu and the custom tiles will be displayed..
        /// </summary>
        public static string MessageProcessedApplications {
            get {
                return ResourceManager.GetString("MessageProcessedApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0}/{1} application(s) ({2}). Tiles have been successfully reset..
        /// </summary>
        public static string MessageResetTiles {
            get {
                return ResourceManager.GetString("MessageResetTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing tiles.
        /// </summary>
        public static string SettingsOverwrite {
            get {
                return ResourceManager.GetString("SettingsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications shortcuts locations.
        /// </summary>
        public static string SettingsShortcutsLocations {
            get {
                return ResourceManager.GetString("SettingsShortcutsLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize tiles.
        /// </summary>
        public static string TitleCustomizeTiles {
            get {
                return ResourceManager.GetString("TitleCustomizeTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select applications to customize.
        /// </summary>
        public static string TitleSelectApps {
            get {
                return ResourceManager.GetString("TitleSelectApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile generation.
        /// </summary>
        public static string TitleTileGeneration {
            get {
                return ResourceManager.GetString("TitleTileGeneration", resourceCulture);
            }
        }
    }
}
