//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tile.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tile.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;7-Zip&quot;: {
        ///        &quot;ShortcutRegex&quot;: &quot;7-Zip File Manager&quot;,
        ///        &quot;IconPath&quot;: &quot;Icons/7-Zip.png&quot;,
        ///        &quot;BackgroundColor&quot;: &quot;#111111&quot;,
        ///        &quot;ForegroundText&quot;: &quot;Light&quot;,
        ///        &quot;ShowNameOnMediumTile&quot;: true,
        ///        &quot;GenerationMode&quot;: &quot;Adjusted&quot;
        ///    },
        ///    &quot;Adobe After Effects&quot;: {
        ///        &quot;ShortcutRegex&quot;: &quot;After Effects&quot;,
        ///        &quot;IconPath&quot;: &quot;Icons/AdobeAfterEffects_alt.png&quot;,
        ///        &quot;BackgroundColor&quot;: &quot;#391f4e&quot;,
        ///        &quot;ForegroundText&quot;: &quot;Light&quot;,
        ///        &quot;ShowNameOnMediumTile&quot;: true,
        ///        &quot;Generati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TilesConfiguration {
            get {
                return ResourceManager.GetString("TilesConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Application xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;VisualElements
        ///		BackgroundColor=&quot;{BackgroundColor}&quot;
        ///		ShowNameOnSquare150x150Logo=&quot;{ShowNameOnSquare150x150Logo}&quot;
        ///		ForegroundText=&quot;{ForegroundText}&quot;
        ///		Square150x150Logo=&quot;{Square150x150Logo}&quot;	
        ///		Square70x70Logo=&quot;{Square70x70Logo}&quot;/&gt;
        ///&lt;/Application&gt;.
        /// </summary>
        internal static string VisualElementsManifest {
            get {
                return ResourceManager.GetString("VisualElementsManifest", resourceCulture);
            }
        }
    }
}
